# Generated by Django 2.2.3 on 2022-02-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220202_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sem',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II')], max_length=6, null=True),
        ),
    ]
